export const TYPES = {
    Application: Symbol.for('Application'),
    OpenAIClient: Symbol.for('OpenAI'),
    MongoClient: Symbol.for('MongoClient'),
    WwebClient: Symbol.for('WwebClient'),
    AuthenticationListener: Symbol.for('AuthenticationListener'),
    MessageObserver: Symbol.for('MessageObserver'),
    MessageCreateListener: Symbol.for('MessageCreateListener'),
    MessageRevokeListener: Symbol.for('MessageRevokeListener'),
    ConfigsRepository: Symbol.for('ConfigsRepository'),
    MessageRepository: Symbol.for('MessageRepository'),
    MembersRepository: Symbol.for('NumberPermissionRepository'),
    GroupMembersRepository: Symbol.for('GroupMembersRepository'),
    ResponseService: Symbol.for('ResponseService'),
    AudioService: Symbol.for('AudioService'),
    TranscriptionService: Symbol.for('TranscriptionService'),
    BotHandler: Symbol.for('BotHandler'),
    FalaHandler: Symbol.for('FalaHandler'),
    RankingHandler: Symbol.for('RankingHandler'),
    DeuitaHandler: Symbol.for('DeuitaHandler'),
    GilsoHandler: Symbol.for('GilsoHandler'),
    TranscreverHandler: Symbol.for('TranscreverHandler'),
};
