export const TYPES = {
    Application: Symbol.for('Application'),
    Logger: Symbol.for('Logger'),
    OpenAIClient: Symbol.for('OpenAI'),
    MongoClient: Symbol.for('MongoClient'),
    WwebClient: Symbol.for('WwebClient'),
    AuthenticationListener: Symbol.for('AuthenticationListener'),
    MessageObserver: Symbol.for('MessageObserver'),
    MessageCreateListener: Symbol.for('MessageCreateListener'),
    ConfigsRepository: Symbol.for('ConfigsRepository'),
    ContactsRepository: Symbol.for('ContactsRepository'),
    ResponseService: Symbol.for('ResponseService'),
    PingHandler: Symbol.for('PingHandler'),
    NotificarHandler: Symbol.for('NotificarHandler'),
    ContatosHandler: Symbol.for('ContatosHandler'),
};
